### ISSUE TITLE
ApiDefinitions.cs file missing.

### ISSUE THREAD

**Issue by AnthonyNjuguna** [colbylwilliams/Xamarin.TTTAttributedLabel#1]
I am trying to build the solution however it errors that the ApiDefinitions.cs file is missing. I searched for it but could not find it.

**Comment by colbylwilliams** [comment]
That file is generated by the Makefile.  Did you run `make` in the extern directory as [described](https://github.com/colbylwilliams/Xamarin.TTTAttributedLabel#building) in the [Readme](https://github.com/colbylwilliams/Xamarin.TTTAttributedLabel/blob/master/README.md)?  Also, I'd highly recommend using the [NuGet package](https://www.nuget.org/packages/Xamarin.TTTAttributedLabel) or [Component](https://components.xamarin.com/view/tttattributedlabel) instead of building manually.

**Comment by AnthonyNjuguna** [comment]
I did run the `make` in the extern directory as described in the Readme. However it threw the following error

```
mkdir -p Release-binding
sharpie bind \
        -n Xamarin.TTTAttributedLabel \
        -o Release-binding \
        -sdk iphoneos \
        TTTAttributedLabel/TTTAttributedLabel/TTTAttributedLabel.h
make: sharpie: No such file or directory
make: *** [Release-binding/ApiDefinitions.cs] Error 1
```

I am using the Nuget but wanted to learn using binding with your code. :)

**Comment by colbylwilliams** [comment]
Looks like ObjectiveSharpie failed (you may not have it installed) but I've added ApiDefinitions.cs to repo and updated the `Makefile` to use it.  You should be able to build now.
